---
sidebar: sidebar 
permalink: create-sandbox-clone.html 
keywords: create, clone, sandbox 
summary: 在NetApp Workload Factory for Databases 中建立沙盒克隆。 
---
= 在NetApp Workload Factory for Databases 中建立沙盒克隆
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
透過在NetApp Workload Factory for Databases 中建立資料庫的沙盒克隆，您可以使用克隆進行開發、測試、整合、分析、培訓、品質保證等，而無需更改來源資料庫。

.關於這項工作
沙箱複本是從來源資料庫上最新的快照建立而成。它可以複製到與來源資料庫相同的 Microsoft SQL Server 中、或是複製到另一個 Microsoft SQL Server 中、只要它們共用相同的適用於 ONTAP 檔案系統的 FSX 即可。

.開始之前
建立沙箱複本之前、請務必先完成下列先決條件。

* *憑證和權限*：您必須擁有link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS 帳戶憑證和「唯讀」或「讀取/寫入」模式權限"^]在 Workload Factory 中建立沙盒克隆。
+
或者，您可以使用 Codebox 複製部分完成的模板或建立已完成的模板，以便您可以使用 REST API 在 Workload Factory 之外建立沙盒克隆。link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["深入瞭解 CodeBox 自動化"^] 。

* *Microsoft SQL Server*：您必須在 Workload Factory for Databases 中擁有託管的 Microsoft SQL Server 來託管新的沙盒複製。
* *AWS Systems Manager*：確保 `NT Authority\SYSTEM`透過 AWS Systems Manager 在 Microsoft SQL 主機中啟用使用者權限。
* *來源資料庫*：您需要一個可用於複製的來源資料庫。


.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在「資料庫」方塊中、選取 * 前往資料庫庫存 * 。
. 在資料庫中、選取 * 沙箱 * 標籤。
. 在沙箱標籤中、選取 * 建立新的沙箱 * 。
. 在 [ 建立新的沙箱 ] 頁面的 [ 資料庫來源 ] 底下，提供下列項目：
+
.. * 來源資料庫主機 * ：選取來源資料庫主機。
.. * 來源資料庫執行個體 * ：選取來源資料庫執行個體。
.. * 來源資料庫 * ：選取要從中複製的來源資料庫。


. 在 Database target （資料庫目標）下、提供下列項目：
+
.. * 目標資料庫主機 * ：為同一 VPC 中的沙箱複製選取目標資料庫主機、並將 ONTAP 檔案系統的 FSX 與來源主機相同。
.. * 目標資料庫執行個體 * ：選取沙箱複製的目標資料庫執行個體。
.. * 目標資料庫 * ：輸入沙箱複製的名稱。


. *安裝*：當複製具有多個資料和/或日誌檔案的 SQL 資料庫時，Workload Factory 會複製自動指派或定義的磁碟機號碼下的所有檔案。
+
選取下列其中一個選項：

+
.. * 自動指派掛載點 *
.. * 定義掛載點路徑 *
+
請提供下列資訊來定義掛載點路徑：

+
*** 輸入資料檔案路徑的磁碟機代號。
*** 輸入記錄檔路徑的磁碟機代號。




. * 定義標記 * ：選取標記以定義沙箱複製。
. 按一下「 * 建立 * 」。


若要檢查工作進度、請前往 * 工作監控 * 標籤。
