---
sidebar: sidebar 
permalink: create-postgresql-server.html 
keywords: create, server, PostgreSQL, deploy, host, deploy a database host, database host 
summary: 在 BlueXP  工作負載工廠內為資料庫建立新的 PostgreSQL SQL 伺服器。 
---
= 在 BlueXP  工作負載工廠中建立 PostgreSQL 伺服器
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在 BlueXP  工作負載工廠中為資料庫建立新的 PostgreSQL 伺服器或資料庫主機，需要使用 FSX 進行 ONTAP 檔案系統部署，並為 Active Directory 建立資源。

.關於這項工作
您需要 AWS 帳戶認證和 _ 自動化 _ 權限。

開始之前，請先瞭解資料庫主機組態， Active Directory 部署，工作負載原廠操作模式的可用儲存部署類型，以及完成此作業的需求。

適用於 ONTAP 檔案系統部署的 FSX:: 若要建立新的 PostgreSQL 伺服器，需要將 ONTAP 檔案系統的 FSX 作為儲存後端。您可以使用現有的適用於 ONTAP 檔案系統的 FSX 、或建立新的檔案系統。如果您選擇現有的 ONTAP 檔案系統 FSX 作為資料庫伺服器儲存後端，我們會為 PostgreSQL 工作負載建立新的儲存 VM 。
+
--
適用於 ONTAP 檔案系統的 FSX 支援 PostgreSQL 的 _standonstle_ 部署。工作負載工廠會為 ONTAP 檔案系統建立單一可用性區域 FSX ，並為資料，記錄和 tempdb 檔案建立個別的磁碟區和 LUN 。

--
工作負載原廠操作模式:: 工作負載工廠提供三種作業模式，視您在工廠管理工作負載時的舒適程度而定。
+
--
*_Basic_ 模式 * ：在此作業模式中，您不需要在工作負載工廠中建立任何 AWS 帳戶認證的關聯。您可以從 Codebox 複製或下載部分填寫的 YAML 範本，以便在工作負載工廠以外完成。

* 讀取模式 * ：在此作業模式中、您會提供具有讀取權限的 AWS 帳戶認證、讓您完成 _ 快速建立 _ 或 _ 進階建立 _ 表單、然後複製或下載表單。您也可以從工作負載工廠重新導向至 CloudForformation ，其中包含完整的表單詳細資料。您將能夠在工作負載工廠中管理部署的資料庫伺服器。

*_AILUSE_ 模式 * ：在這種作業模式中，您可以提供 AWS 帳戶認證及自動化權限，讓您在工作負載工廠內建立及管理 AWS 資源。

--


.開始之前
在建立新的資料庫主機之前、請確定您具備下列先決條件。

認證和權限:: 您必須link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS 帳戶認證和自動模式權限"^]在工作負載工廠中建立新的資料庫主機。




== 建立資料庫伺服器

您可以使用 _ 進階建立 _ 部署模式，在工作負載工廠以 _ 自動化 _ 模式權限完成這項工作。您也可以使用 Codebox 中提供的下列工具： REST API ， AWS CLI 和 AWS CloudForgation 。link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["瞭解如何使用 Codebox 進行自動化"^]。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在「資料庫」方塊中，選取 * 部署資料庫主機 * ，然後從下拉式功能表中選取 * PostgreSQL * 。
. 選取 * 進階建立 * 。
. 對於 * 部署模型 * ，預設為 * 獨立執行個體 * 。
. 在 * AWS 設定 * 下、提供下列項目：
+
.. * AWS 認證 * ：選取具有自動化權限的 AWS 認證來部署新的資料庫主機。
+
AWS 認證加上 _ 自動化 _ 權限，可讓工作負載在出廠時從工作負載工廠內的 AWS 帳戶部署及管理新的資料庫主機。

+
具有 _ 讀取 _ 權限的 AWS 認證可讓工作負載工廠產生 CloudForgation 範本，供您在 AWS CloudForgation 主控台中使用。

+
如果您在工作負載工廠中沒有相關的 AWS 認證，而且想要在工作負載工廠中建立新的伺服器，請依照 * 選項 1* 前往認證頁面。為資料庫工作負載手動新增 _ 自動化 _ 模式所需的認證和權限。

+
如果您想要在工作負載工廠中完成建立新伺服器表單，以便下載完整的 YAML 檔案範本，以便在 AWS CloudForformation 中部署，請遵循 * 選項 2* ，以確保您擁有在 AWS CloudForformation 中建立新伺服器所需的權限。為資料庫工作負載手動新增 _Read_ 模式所需的認證和權限。

+
或者，您也可以從 Codebox 下載部分完成的 YAML 檔案範本，在工作負載工廠外部建立堆疊，而無需任何認證或權限。從 Codebox 的下拉式清單中選取 * CloudForiam* 以下載 YAML 檔案。

.. * 地區與 VPC* ：選擇地區與 VPC 網路。
+
確保現有介面端點的安全性群組允許存取所選子網路的 HTTPS （ 443 ）傳輸協定。

+
AWS 服務介面端點（ SQS 、 FSX 、 EC2 、 CloudWatch 、雲端形成、 SSM) 和 S3 閘道端點會在部署期間建立（如果找不到）。

+
VPC DNS 屬性 `EnableDnsSupport` 並 `EnableDnsHostnames` 經過修改、以啟用解析端點位址解析（如果尚未設定為 `true`）。

.. * 可用性區域 * ：選擇可用性區域和子網路。
+
適用於單一執行個體部署::
+
--
... 在 * 叢集組態 - 節點 1* 欄位中，從 * 可用性區域 * 下拉式功能表中選取可用性區域，並從 * 子網路 * 下拉式功能表中選取子網路。


--


.. * 安全性群組 * ：選取現有的安全性群組或建立新的安全性群組。
+
在新伺服器部署期間，會將兩個安全群組附加至 SQL 節點（ EC2 執行個體）。

+
... 建立工作負載安全群組，以允許 PostgreSQL 所需的連接埠和通訊協定。
... 對於現有的 ONTAP 檔案系統 FSX ，與其相關的安全性群組會自動新增至 PostgreSQL 節點，以便與檔案系統進行通訊。建立適用於 ONTAP 系統的新 FSX 時，會為適用於 ONTAP 檔案系統的 FSX 建立新的安全性群組，而同一個安全性群組也會附加至 SQL 節點。




. 在 * 應用程式設定 * 下、提供下列項目：
+
.. 從下拉式功能表中選取 * 作業系統 * 。
.. 從下拉式功能表中選取 * PostgreSQL 版本 * 。
.. * 資料庫伺服器名稱 * ：輸入資料庫叢集名稱。
.. * 資料庫認證 * ：輸入新服務帳戶的使用者名稱和密碼、或使用 Active Directory 中現有的服務帳戶認證。


. 在 * 連線 * 下，選取金鑰配對以安全地連線至執行個體。
. 在 * 基礎架構設定 * 下、提供下列項目：
+
.. * 資料庫執行個體類型 * ：從下拉式功能表中選取資料庫執行個體類型。
.. *FSX for ONTAP System* ：為 ONTAP 檔案系統建立新的 FSX 、或使用現有的 FSX for ONTAP 檔案系統。
+
... * 為 ONTAP * 建立新的 FSX ：輸入使用者名稱和密碼。
+
適用於 ONTAP 檔案系統的全新 FSX 可能會增加 30 分鐘以上的安裝時間。

... * 為 ONTAP * 選擇現有的 FSX ：從下拉式功能表中選取適用於 ONTAP 名稱的 FSX 、然後輸入檔案系統的使用者名稱和密碼。
+
對於現有的 ONTAP 檔案系統 FSX 、請確保下列事項：

+
**** 連接到適用於 ONTAP 的 FSX 的路由群組可讓路由傳送至子網路以用於部署。
**** 安全性群組允許來自用於部署的子網路流量、特別是 HTTPS （ 443 ）和 iSCSI （ 3260 ） TCP 連接埠。




.. * Snapshot polic*: 默認啓用。快照每天拍攝、保留期為 7 天。
+
快照會指派給為 PostgreSQL 工作負載所建立的磁碟區。

.. * 資料磁碟機大小 * ：輸入資料磁碟機容量、然後選取容量單位。
.. * 已配置的 IOPS * ：選擇 * 自動 * 或 * 使用者已配置 * 。如果您選取 * 使用者佈建 * 、請輸入 IOPS 值。
.. * 處理量容量 * ：從下拉式功能表中選取處理量容量。
+
在某些地區、您可以選擇 4 Gbps 的處理量容量。若要配置 4 Gbps 的處理量容量、您的 ONTAP 檔案系統 FSX 必須設定至少 5 、 120 GiB 的 SSD 儲存容量和 16 、 000 SSD IOPS 。

.. * 加密 * ：從您的帳戶中選取金鑰、或從其他帳戶選取金鑰。您必須從其他帳戶輸入加密金鑰 ARN 。
+
ONTAP 的 FSX 自訂加密金鑰並未根據服務適用性列出。選取適當的 FSX 加密金鑰。非 FSX 加密金鑰將導致伺服器建立失敗。

+
AWS 託管金鑰會根據服務適用性進行篩選。

.. * 標記 * ：您可以選擇性地新增最多 40 個標記。
.. * 簡易通知服務 * ：您也可以選擇從下拉式功能表中選取 Microsoft SQL Server 的 SNS 主題、為此組態啟用簡易通知服務（ SNS ）。
+
... 啟用 Simple Notification Service 。
... 從下拉式功能表中選取 ARN 。


.. * CloudWatch 監控 * ：您也可以選擇啟用 CloudWatch 監控功能。
+
我們建議您啟用 CloudWatch 、以便在發生故障時進行除錯。AWS CloudForecation 主控台中出現的事件屬於高層級、並未指定根本原因。所有詳細記錄都會儲存在 `C:\cfn\logs` EC2 執行個體的資料夾中。

+
在 CloudWatch 中、會建立一個記錄群組、其中包含堆疊的名稱。每個驗證節點和 SQL 節點的記錄串流都會出現在記錄群組下方。CloudWatch 會顯示指令碼進度、並提供相關資訊、協助您瞭解部署是否失敗。

.. * 資源復原 * ：目前不支援此功能。


. 摘要
+
.. * 預估成本 * ：提供部署所示資源時可能會產生的費用預估。


. 按一下 * 建立 * 以部署新的資料庫主機。
+
或者、您也可以儲存組態。


