---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, databases 
summary: 已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。 
---
= 資料庫的 BlueXP  工作負載工廠已知限制
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。



== AMI 映像版本支援

我們僅針對每個 SQL 版本顯示最多四個最新版本或 AMI 影像修訂版。我們不允許從早於最新四個版本的 AMI 映像進行安裝。



== 自訂 AMI

使用自訂 AMI 進行部署時、假設映像中存在安裝媒體。這是 FCI 組態所需的原因如下：

* 若要解除安裝並重新設定、以形成 FCI 叢集
* 在映像中選取獨立部署的定序集以外的定序集時


在部署過程中，工作負載工廠不會安裝含有多個 Microsoft SQL Server 執行個體的自訂 AMI 。只會選取預設的 Microsoft SQL Server 執行個體、並將其設定為部署的一部分。



== 請針對失敗的部署進行回溯與重試

工作負載原廠不支援復原和重試失敗的部署。您可以從 AWS 中的 CloudForgation 主控台回溯或重試失敗的堆疊。



== Active Directory 和 DNS 資源復原

當您從 AWS 的 CloudForgation 主控台回溯測試或部署失敗時、下列 DNS 資源不會從 Active Directory 和 DNS 中移除：

* 將 SQL 部署的每個節點部署到其管理 IP 位址
* 在 FCI 的情況下、將 Windows 叢集名稱移至 EC2 執行個體的保留次要 IP 位址
* SQL FCI 名稱會將兩個 EC2 執行個體的兩個保留 IP 位址都保留在 FCI 中


您需要手動清理這些項目、或等待網域清除過時的項目。



== 始終可用性群組組組態支援

工作負載原廠不支援管理 Always On Availability Groups 組態。



== 使用者管理的 Active Directory 安全性群組

如果您在工作負載工廠的 Microsoft SQL Server 部署期間選取「使用者管理的 Active Directory 」，則必須提供安全群組，允許 EC2 執行個體之間的流量傳輸至目錄服務進行部署。工作負載工廠不會像 AWS 託管的 Microsoft AD 一樣，自動附加使用者託管 Active Directory 的安全群組。



== 自訂加密金鑰

ONTAP 適用的 FSX 自訂加密金鑰並未根據服務適用性列出。您必須選擇適當的金鑰。AWS 託管金鑰會根據服務的適用性進行篩選。



== CloudForgation 範本

下載或複製的 Codebox 產生的 CloudForgation 範本（ YAML 檔案）的保留期限有限、只有七天。



== 沙箱支援

可從資料庫伺服器建立的沙箱複本數量上限為 90 個。



== Microsoft SQL Server 偵測與管理

未儲存 Microsoft SQL Server 偵測。每次您存取工作負載工廠中的資料庫時， Microsoft SQL Server 偵測會再次執行，以識別區域中的 SQL 安裝。



== 探索節約效益

在 [ 詳細目錄 ] 索引標籤中，針對每個 Microsoft SQL 執行個體所顯示的預估成本，是在 ONTAP 檔案系統層級的 FSX 計算，而非託管 SQL 執行個體的磁碟區計算。



== 多個適用於 ONTAP 檔案系統的 FSX

Workload Factory 不支援建立或儲存具有多個適用於 ONTAP 檔案系統之 FSX 的 Microsoft SQL Server 組態。僅支援一個用於 ONTAP 檔案系統組態部署的 FSX 。



== 使用 Terraform 在私有網路中部署 Microsoft SQL Server 的區域可用度

Microsoft SQL Server 部署在沒有使用 Terraform 輸出連線的私有網路中、僅在 us-east-1 （ N.Virginia ）地區支援。PostgreSQL 不支援 Amazon CloudWatch 或在私有網路中部署。
