---
sidebar: sidebar 
permalink: learn-databases.html 
keywords: Databases 
summary: NetApp Workload Factory for Databases 是一種端到端資料庫部署和維護服務，具有內建的最佳化最佳實踐、自動精簡克隆以及監控和解決功能。 
---
= 了解NetApp資料庫工作負載工廠
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases 是一種端到端資料庫部署和維護服務，具有內建的最佳化最佳實踐、自動精簡克隆以及監控和解決功能。



[[what-is-netapp-workload-factory-for-databases]]
== 什麼是NetApp Workload Factory for Databases？

NetApp Workload Factory for Databases 可發現、評估、規劃、配置及移轉 Microsoft SQL Server、PostgreSQL 和 Oracle 資料至 Amazon FSx for NetApp ONTAP（FSx for ONTAP）部署，這些部署經過最佳化，可滿足您的效能與成本預期，同時遵循業界最佳實踐。NetApp Workload Factory for Databases 持續在 FSx for ONTAP 上最佳化並管理資料庫。

有關 Workload Factory 的更多信息，請參閱link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["工作負載工廠概述"^]。



[[workload-factory-benefits-for-self-managed-databases]]
== 工作負載工廠為自管理資料庫帶來的優勢

Workload Factory 為自我管理的資料庫提供最佳實務做法和自動化功能。



[[best-practices]]
=== 最佳實務做法

* AWS Cloud 、 Microsoft Windows 和 SQL 伺服器、以及 NetApp ONTAP 在 EC2 執行個體上部署 SQL Server 的整合式知識。
* 整體擁有成本最佳化部署。
* 遵循 AWS 、 Microsoft 和 ONTAP 最佳實務做法的端點對端部署自動化。
* _快速建立_部署模式可協助您避免手動配置的潛在陷阱。




[[automation-with-workload-factory-codebox]]
=== 使用 Workload Factory Codebox 實現自動化

Workload Factory 透過 _Codebox_ 引入了內建自動化功能。  Codebox 具有以下自動化優勢：

* *程式碼片段產生*：Workload Factory 在資源建立期間產生基礎架構即程式碼（IaC）片段，從而實現與現有協調工作流程的無縫整合。
* *基礎架構即程式碼副駕駛*：Codebox 是一個基礎架構即程式碼 (IaC) 副駕駛，可協助開發人員和 DevOps 產生程式碼來執行 Workload Factory 支援的任何操作。
* * 程式碼檢視器與自動化目錄 * ： Codebox 提供程式碼檢視器、可快速分析自動化、並提供自動化目錄、供日後快速重複使用。




[[workload-factory-for-databases-features]]
=== 資料庫工作負載工廠功能

資料庫工作負載工廠提供以下功能：

* *成本估算*：使用節省計算器評估潛在的成本節省，該計算器估算並詳細列出現有 Microsoft SQL Server 和 Oracle 部署（使用 Elastic Block Store、FSx for Windows File Server 和內部部署）與 FSx for ONTAP 相比的儲存、運算、SQL 授權、快照和複製的逐項成本。
* *簡單、快速的部署*：透過內建的 NetApp、Microsoft 和 Amazon 最佳實踐，簡化和最佳化主機、資料庫和沙箱的配置，消除在 AWS 上對 Microsoft SQL Server 和 PostgreSQL 執行個體進行手動配置的複雜性。
+
** 使用 Workload Factory 控制台的 _Quick_ 或 _Advanced_ 建立模式進行部署，或透過 Codebox 建立、重複使用和自訂 AWS CloudFormation 範本，以便在多個環境中進行未來的部署。
** 按需建立隔離資料庫，提供儲存配置和沙箱複本，可用於測試、整合、診斷和培訓，而不會影響正式作業資料。


* *Well-architected 評估功能*：持續掃描您的 Microsoft SQL Server 和 Oracle 環境，產生包含洞察、機會和建議的綜合報告，協助您根據 AWS 最佳實務做法實現卓越營運、安全性、可靠性、效能效率和成本最佳化。
* *錯誤分析*：使用 AI 分析器分析和疑難排解記錄錯誤，以取得詳細的錯誤訊息、疑難排解步驟和解決問題的建議。
* *集中管理*：在一個位置即可管理 FSx for ONTAP 上的 Microsoft SQL Server、Oracle 和 PostgreSQL 資源。在 Workload Factory 中，您可以查看已連線的基礎架構、AWS 帳戶、憑證、已連線的 FSx for ONTAP 檔案系統、儲存使用情況（包括 NFS 磁碟區和 iSCSI LUN）、保護狀態、效能、架構良好狀態和錯誤分析。




[[benefits-of-amazon-fsx-for-ontap-for-self-managed-databases]]
== Amazon FSX for ONTAP 的優點、適用於自行管理的資料庫

* * 耐用性、可用度及可靠性 * ：適用於 ONTAP 的 FSX 提供多項功能、可提升在適用於 ONTAP 的 FSX 上託管的自我管理資料庫的耐用性與可用度、例如支援單一和多重可用性區域部署的高可用度、應用程式感知快照、使用複寫改善災難恢復、以及有效率的備份。
* * 效能與擴充性 * ：適用於 ONTAP 的 FSX 提供高處理量、低延遲、高速網路連線、以及多個檔案系統的擴充性等效能最佳化功能、可擴充工作負載所需的彙總效能。
* * 資料管理與效率 * ：適用於 ONTAP 的 FSX 提供多項功能、可強化資料管理與效率、例如節省空間的精簡型複本、精簡配置、壓縮與重複資料刪除、以及將不常存取的資料分層至容量集區。


link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html["了解適用於 Workload Factory 的 FSx for ONTAP"^] 。



[[tools-to-use-netapp-workload-factory]]
== 使用NetApp Workload Factory 的工具

您可以將NetApp Workload Factory 與以下工具一起使用：

* *Workload Factory 控制台*：Workload Factory 控制台提供您的應用程式和專案的視覺化、整體視圖。
* * NetApp控制台*： NetApp控制台提供混合介面體驗，以便您可以將 Workload Factory 與其他NetApp資料服務一起使用。
* *問我*：使用問我 AI 助理來提問並了解有關 Workload Factory 的更多信息，而無需離開 Workload Factory 控制台。從 Workload Factory 幫助選單中存取「問我」。
* *CloudShell CLI*：Workload Factory 包含 CloudShell CLI，可透過基於瀏覽器的單一 CLI 跨帳號管理和操作 AWS 和NetApp環境。從 Workload Factory 控制台頂部欄存取 CloudShell。
* *REST API*：使用 Workload Factory REST API 部署和管理您的 FSx for ONTAP檔案系統和其他 AWS 資源。
* *CloudFormation*：使用 AWS CloudFormation 程式碼執行您在 Workload Factory 控制台中定義的操作，以從您的 AWS 帳戶中的 CloudFormation 堆疊對 AWS 和第三方資源進行建模、配置和管理。
* *Terraform NetApp Workload Factory 提供者*：使用 Terraform 建置和管理在 Workload Factory 控制台中產生的基礎架構工作流程。




[[supported-configurations]]
== 支援的組態

您可以按照 AWS、NetApp ONTAP、Microsoft SQL Server、Oracle 和 PostgreSQL 的最佳實踐，將 Workload Factory 與下列資料庫引擎、版本、作業系統和部署模型一起使用。

[cols="1,1,1,1"]
|===
| 引擎 | 版本 | 作業系統 | 部署模型 


| Microsoft SQL Server | 2016年SQL Server | Windows Server 2016 | FCI、獨立式 


| Microsoft SQL Server | 2019年SQL Server | Windows Server 2016 | FCI、獨立式 


| Microsoft SQL Server | 2022年SQL Server | Windows Server 2016 | FCI、獨立式 


| Microsoft SQL Server | 2016年SQL Server | Windows Server 2019 | FCI、獨立式 


| Microsoft SQL Server | 2019年SQL Server | Windows Server 2019 | FCI、獨立式 


| Microsoft SQL Server | 2022年SQL Server | Windows Server 2019 | FCI、獨立式 


| Microsoft SQL Server | 2016年SQL Server | Windows Server 2022 | FCI、獨立式 


| Microsoft SQL Server | 2019年SQL Server | Windows Server 2022 | FCI、獨立式 


| Microsoft SQL Server | 2022年SQL Server | Windows Server 2022 | FCI、獨立式 


| Microsoft SQL Server | SQL 伺服器 2017 | 任何 | FCI、獨立式 


| Microsoft SQL Server | SQL Server 2016、2017、2019、2022 | 任何 | FCI、獨立式 


| Microsoft SQL Server | SQL Server 2016、2017、2019、2022 | 任何 | Always On 可用性群組 


| 甲骨文 | 19c | RHEL、SuSe Linux | 獨立（單/多租戶） 


| 甲骨文 | 21c | RHEL、SuSe Linux | 獨立（單/多租戶） 


| 甲骨文 | 19c | RHEL、SuSe Linux | 獨立（單/多租戶） 


| 甲骨文 | 21c | RHEL、SuSe Linux | 獨立（單/多租戶） 


| 甲骨文 | 19c | RHEL、SuSe Linux | 獨立於 ASM（單/多租戶） 


| 甲骨文 | 21c | RHEL、SuSe Linux | 獨立於 ASM（單/多租戶） 


| 甲骨文 | 19c、21c | RHEL、SuSe Linux | Data Guard 


| PostgreSQL | PostgreSQL 15 | 亞馬遜 Linux 2023 AMI | HA，獨立實例 


| PostgreSQL | PostgreSQL 16 | 亞馬遜 Linux 2023 AMI | HA，獨立實例 
|===


[[integrated-aws-services]]
== 整合式 AWS 服務

資料庫包含以下整合的 AWS 服務：

* CloudForation
* 簡單通知服務
* CloudWatch
* Systems Manager
* Secrets Manager




[[regions]]
== 區域

支援 ONTAP 適用的 FSX 的所有商業地區均支援資料庫。 https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["檢視支援的Amazon地區。"^]

不支援下列 AWS 區域：

* 中國地區
* 秘密雲端
* Top Secret Cloud




[[getting-help]]
== 取得協助

Amazon FSX for NetApp ONTAP 的功能是AWS的第一方解決方案。如需與適用於 ONTAP 檔案系統、基礎架構或任何使用此服務的解決方案的 FSX 相關的問題或技術支援問題、請使用 AWS 管理主控台的支援中心、開啟 AWS 的支援案例。選取「FSXfor ONTAP Sf1」服務和適當的類別。提供建立AWS支援案例所需的其餘資訊。

有關 Workload Factory 或 Workload Factory 應用程式和服務的一般問題，請參閱link:get-help.html["取得有關NetApp Workload Factory for Databases 的協助"]。
