---
sidebar: sidebar 
permalink: optimize-overview.html 
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance 
summary: 資料庫工作負載工廠會定期分析 Microsoft SQL Server 和 Oracle 配置以確定是否有任何問題。 
---
= Workload Factory 中的資料庫環境配置分析
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
資料庫工作負載工廠會定期分析資料庫配置，以確定Amazon FSx for NetApp ONTAP儲存上的 Microsoft SQL Server 和 Oracle 部署是否有任何問題。當發現問題時，Workload Factory 會向您展示問題所在，並解釋需要進行哪些更改以確保您的資料庫配置達到最佳效能、成本效益並符合最佳實踐。

主要功能包括：

* 每日組態分析
* 自動最佳實務驗證
* 適當調整規模的建議
* 主動觀察
* 行動洞見
* AWS 架構良好的架構顧問




== 配置分析的組成部分

配置分析包括以下幾個組成部分：

架構良好的狀態:: 架構良好狀態指的是資料庫配置的整體健康狀況；配置分為「已最佳化」、「未最佳化」或「過度配置」三類。在 Workload Factory 控制台中，可以從 Microsoft SQL Server 執行個體或 Oracle 資料庫中查看配置的良好架構狀態。
架構良好的分數:: 得分包括所有目前已分析的配置，並以百分比形式顯示。25% 的得分意味著 25% 的資料庫部署架構良好。架構良好評分可從「架構良好」畫面以及 Workload Factory 控制台中的 Microsoft SQL Server 執行個體或 Oracle 資料庫中取得。
組態類別:: 配置分為以下幾類：儲存、運算、應用、彈性、克隆。每個類別都包含特定的配置評估，這些評估會定期進行分析。配置類別可以從「架構完善」畫面以及工作負載工廠控制台中的 Microsoft SQL Server 執行個體或 Oracle 資料庫中進行參考。




== 分析範圍

最佳化的範圍會因評估的元件而異。例如、儲存最佳化是在 SQL 執行個體層級進行、而運算最佳化則是在主機層級進行。



== 分析需求

為了進行完整的資料庫環境分析，資源必須註冊並在線。

link:register-instance.html["了解如何註冊資源。"]

.下一步
link:optimize-configurations.html["實施結構良好的資料庫配置"]
