---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: 資料庫的 BlueXP  工作負載工廠會掃描 Microsoft SQL Server 組態，提供深入分析和建議，協助您達到卓越營運績效。 
---
= 最佳化 Microsoft SQL Server 部署的組態
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
資料庫的 BlueXP  工作負載工廠會持續掃描並評估執行於 Amazon FSX for NetApp ONTAP 上的 Microsoft SQL Server 部署組態。此功能提供深入分析和建議，可選擇自動最佳化未最佳化的組態，讓您的資料庫工作負載達到卓越的營運表現。

.關於這項工作
此評估會針對 Microsoft SQL Server 執行個體、自動且持續地執行一次、其 FSX 適用於在工作負載工廠中管理的 ONTAP 儲存設備。只有在部署後或管理執行個體之後執行每日排程工作時、才能在最佳化儀表板中使用評估報告。

工作負載工廠根據適用於 ONTAP 儲存設備的 FSX 最佳實務、提供最佳組態最佳化的詳細建議。您可以檢閱建議，並選擇最佳化未最佳化的組態。

掃描內容:: 工作負載工廠會評估下列 Microsoft SQL Server 執行個體組態的最佳化狀態：
+
--
* 儲存規模：包括儲存層、檔案系統保留空間、記錄磁碟機大小及 TempDB 磁碟機大小
* 儲存配置：包括使用者資料檔案放置、記錄檔放置及 TempDB 放置
* 儲存組態：包括容量管理、精簡配置、分層原則、快照、多重路徑 I/O 狀態、原則和工作階段等
* 運算：包括正確調整規模，作業系統修補程式，以及接收端調整（ RSS ）和 TCP 卸載等網路介面卡設定
* 應用程式：包括 Microsoft SQL Server 授權， Microsoft SQL Server 修補程式和 MAXDOP 設定
* 恢復能力：包括本機快照，用於 ONTAP 備份的 FSX ，以及跨區域複寫（ CRR ）


--


.開始之前
* 您必須擁有具有讀取或自動化權限的認證。
* 若要評估 Microsoft SQL Server 執行個體的儲存、執行個體必須由工作負載工廠管理、且儲存類型必須為適用於 ONTAP 的 FSX 。
* 在選擇最佳化設定或組態之前、請務必仔細檢閱每項建議。對於 RSS 和 MAXDOP 設定，我們建議您先測試建議的設定，以判斷效能改善，然後再變更正式作業環境。



NOTE: 最佳化程序可能會導致執行個體停機或服務中斷。在您選擇最佳化組態之前，請務必先檢閱最佳化摘要和行動項目。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在「資料庫」方塊中、選取 * 前往資料庫庫存 * 。
. 在 * Inventory （資源清冊） * 選項卡中，選擇下拉箭頭以展開主機行以查看其受管實例。
+
主機隨即展開並顯示主機執行個體。

. 選取執行個體的三點功能表，然後選取 * 最佳化 * 。
. 在 SQL Server 執行個體的最佳化執行個體頁面上，檢閱評估結果。
+
您可以依類別，子類別，狀態，嚴重性和標記進行篩選。

+
您也可以選擇 * 匯出 PDF* 來下載評估結果報告。

. 選取下拉式箭頭以檢視任何組態的建議。請務必仔細檢閱建議內容。
+
本建議說明未最佳化組態的最佳實務做法和潛在陷阱。

. 選擇 * 最佳化 * 未最佳化組態。
+
* 「全選」 * 是預設值，但您可以選取特定資源進行最佳化。

. 檢閱最佳化對話方塊中顯示的最佳化摘要和行動項目、瞭解如果您選擇最佳化、將會發生什麼情況。某些最佳化作業可能會導致執行個體停機或服務中斷。
. 選擇 * 繼續 * 以最佳化組態。


.結果
最佳化程序即會啟動。選取 * 工作監控 * 標籤以檢視作業狀態。
