---
sidebar: sidebar 
permalink: protect-sql-server.html 
keywords: protect, server, Microsoft SQL Server, SQL Server, protect instance, protect database 
summary: 保護 Microsoft SQL Server 執行個體和資料庫。 
---
= 保護 Microsoft SQL Server 工作負載
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
使用來自工作負載工廠控制台的BlueXP backup and recovery保護您的 Microsoft SQL Server 應用程式資料。根據您建立的策略，備份會自動產生並儲存在您的公有或私有雲帳戶的物件儲存中。



== 關於這項工作

BlueXP backup and recovery利用NetApp SnapMirror資料複製技術，透過建立快照副本並將其傳輸到備份位置來確保所有備份完全同步。

有關使用BlueXP backup and recovery進行保護的詳細信息，請參閱link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-mssql-protect-overview.html["使用BlueXP backup and recovery保護 Microsoft SQL 工作負載概述"^]。



== 開始之前

以下是使用BlueXP backup and recovery保護 Microsoft SQL Server 工作負載的要求：

* BlueXP連接器
+
參考link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["了解如何配置BlueXP連接器"^]和link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["標準BlueXP要求"^]。

+
連接器需要 Ubuntu 22.04 LTS 作業系統。

* BlueXP backup and recovery許可證
+
link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-start-licensing.html["設定BlueXP backup and recovery的許可"^]

* 在連接器上設定主機解析
+
若要發現資料庫，您必須在連接器上設定主機解析。在託管設備上，在 `/etc/hosts`文件。





== 保護 Microsoft SQL Server 執行個體和資料庫

保護 Microsoft SQL Server 執行個體和資料庫涉及資源發現、先決條件驗證以及 Microsoft SQL Server 外掛程式的配置和安裝。該外掛程式是NetApp軟體的主機端元件，可讓您保護 Microsoft SQL Server 工作負載。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在「資料庫」方塊中、選取 * 前往資料庫庫存 * 。
. 在資料庫中、選取 * 庫存 * 索引標籤。
. 將*引擎類型*過濾為*Microsoft SQL Server*。
. 從選單中選擇要保護的實例的*保護*。
. 選擇您想要註冊和保護工作負載的*連接器*。
. 為了準備資料保護，工作負載工廠會自動在BlueXP backup and recovery中註冊您的 SQL Server 資源，配置並安裝 Microsoft SQL Server 插件，並發現滿足保護 SQL Server 執行個體的先決條件的資源。選擇“*開始*”來啟動程序。
. 滿足先決條件後，選擇「*重定向*」以重定向到BlueXP backup and recovery。


.下一步
從BlueXP backup and recovery中，建立策略來保護您的 Microsoft SQL Server 執行個體和資料庫。

link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-policies-create.html["了解如何建立策略來保護您的 Microsoft SQL Server 執行個體和資料庫"^] 。

相關信息，請參閱link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-mssql-protect-overview.html["BlueXP backup and recovery文檔"^]用於管理 Microsoft SQL Server 工作負載。
