---
sidebar: sidebar 
permalink: register-instance.html 
keywords: manage, register, Microsoft SQL Server instance, Oracle database, manage database, manage instance 
summary: 註冊資源，以便您可以監控NetApp Workload Factory for Databases 中的資源狀態、資源使用率、保護和儲存效能。 
---
= 在NetApp Workload Factory for Databases 中註冊資源
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
註冊 Microsoft SQL Server 執行個體和 Oracle 資料庫，以便您可以在NetApp Workload Factory for Databases 中監控執行個體和資料庫狀態、資源使用率、保護和儲存效能。

僅在 FSx for ONTAP檔案系統儲存上執行的資料庫引擎才可以註冊。



== 關於任務

註冊實例（SQL Server）或資料庫（Oracle）包括兩個步驟 - 身份驗證和準備。準備工作包括確保所有 AWS、 NetApp和 PowerShell 模組都安裝在實例上。

您可以使用 SQL Server 憑證或 Windows 憑證進行驗證。


NOTE: Workload Factory 僅支援 Microsoft SQL Server 執行個體和 Oracle 資料庫的註冊和管理。根據您在 Workload Factory 中選擇的 AWS 帳戶憑證，PostgreSQL 主機可能會出現在清單中。目前，Workload Factory 僅支援在 Amazon Linux 作業系統上執行的未註冊的 PostgreSQL 執行個體。



== 開始之前

在註冊實例之前請考慮以下事項：

實例或資料庫的主機必須出現在清單中。要讓主機出現在庫存中，您必須 link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["授予_查看、規劃和分析_權限"^] 在您的 AWS 帳戶中。



=== 在私有網路中註冊實例

若要在沒有外部連線的私人網路中註冊執行個體（SQL Server）或資料庫（Oracle），需要在 VPC 中提供下列終端節點，並與 SQL Server 所在的子網路關聯。確保介面端點允許附加的安全群組中的連接埠 443。

* `S3 Gateway/endpoint`
* `ssm`
* `ssmmessages`
* `fsx`
+
如果您對 EC2 執行個體的所有傳出連線都使用 Proxy 伺服器，則必須允許存取下列網域，以便管理作業正常運作：

* ``.microsoft.com``（SQL 伺服器）
* ``.powershellgallery.com``（SQL 伺服器）
* ``.aws.amazon.com``
* ``.amazonaws.com``




== 註冊 SQL Server 實例

註冊實例包括實例認證和準備。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在「資料庫」方塊中、選取 * 前往資料庫庫存 * 。
. 從資料庫選單中，選擇*Inventory*。
. 在清單中，選擇 *Microsoft SQL Server* 作為引擎類型。
. 選擇“*實例*”標籤。
. 選擇註冊單一實例或多個實例。
+
.. 單一實例註冊：導航至要管理的實例並選擇*註冊實例*。
.. 多實例註冊：選擇*註冊多個實例*按鈕。
+
註冊多個實例有兩種方式。兩種情況下，實例必須具有相同的身份驗證狀態（未身份驗證或已身份驗證）。

+
*** 未經身份驗證的實例：選擇多個未經身份驗證的實例進行註冊。這些實例必須共用相同的驗證憑證和 FSx for ONTAP 憑證。選擇“應用”，然後選擇“下一步”。
*** 已認證實例：選擇多個已認證實例進行註冊，然後選擇*下一步*。




. 在「註冊實例」頁面的第 2 步中，選擇實例身份驗證模式，輸入以下詳細信息，然後選擇「下一步」。如果實例已通過身份驗證，請選擇「下一步」。
+
** *SQL Server 驗證*：輸入 SQL Server 使用者名稱和密碼，以及 FSx for ONTAP 檔案系統使用者名稱和密碼。
** *Windows 驗證*：輸入 Windows 使用者名稱和密碼，以及 FSx for ONTAP 檔案系統使用者名稱和密碼。


. 在步驟 3 中，透過確保實例滿足所需的先決條件來準備實例。如果所有必需模組均已安裝且先決條件均已滿足，請選擇「下一步」以註冊實例。如果您需要採取行動，請按照以下步驟操作。
+
.. 如果缺少，請選擇工作負載工廠來*安裝缺少的 AWS 和 NetApp PowerShell 模組*。
.. 如果缺少，請選擇「工作負載工廠」來「安裝缺少的 PowerShell 7」。安裝缺少的 PowerShell 模組 7 需要重新啟動系統。
.. 查看以下功能的先決條件清單。確保您滿足註冊實例的每個功能的所有先決條件。
+
*** *審查精心設計的問題和建議*
*** *修復架構問題*
*** 建立資料庫
*** 建立資料庫副本（沙盒）
+
完成先決條件包括更新您的 AWS IAM 政策權限、EC2 IAM 執行個體設定檔權限、SQL Server 權限和 PowerShell 模組。



.. 當先決條件完成並且檢查*準備就緒*時，您可以選擇*註冊*該實例。




.結果
實例註冊啟動。選擇「作業監控」標籤來追蹤進度。



== 註冊 Oracle 資料庫

註冊資料庫包括實例認證和準備。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在「資料庫」方塊中、選取 * 前往資料庫庫存 * 。
. 從資料庫選單中，選擇*Inventory*。
. 在清單中，選擇 *Oracle* 作為資料庫引擎。
. 選擇“*資料庫*”標籤。
. 選擇註冊單一資料庫或多個資料庫。
+
.. 單一資料庫註冊：導航至要管理的資料庫並選擇*註冊資料庫*。
.. 多資料庫註冊：選擇*註冊多個資料庫*按鈕。
+
有兩個選項可用於註冊多個資料庫。在這兩種情況下，資料庫必須共用相同的身份驗證狀態（未經身份驗證或已驗證）。

+
*** 未經身份驗證的資料庫：選擇多個未經身份驗證的資料庫進行註冊。這些資料庫必須共用相同的驗證憑證和 FSx for ONTAP憑證。選擇“*應用*”，然後選擇“*下一步*”。
*** 已驗證的資料庫：選擇多個已驗證的資料庫進行註冊，然後選擇*下一步*。




. 在註冊資料庫頁面的第 2 步中，選擇資料庫身份驗證模式，輸入以下詳細信息，然後選擇*下一步*。如果資料庫已經過身份驗證，請選擇「下一步」。
+
** *Oracle 使用者驗證*：輸入 Oracle 使用者名稱和密碼，以及 FSx for ONTAP檔案系統使用者名稱和密碼。
** *Oracle ASM 使用者驗證*：可選。如果 Oracle 資料庫使用自動儲存管理 (ASM)，請輸入 Oracle ASM（網格）使用者名稱和密碼。


. 在步驟 3 中，準備資料庫，確保資料庫符合所需的先決條件。如果安裝了所有必要的模組並且滿足先決條件，請選擇「下一步」來註冊資料庫。如果您需要採取行動，請按照以下步驟操作。
+
.. 查看以下功能的先決條件清單。必須滿足單一功能的所有先決條件才能註冊資料庫。
+
*** *審查精心設計的問題和建議*


.. 完成以下先決條件：
+
*** *AWS IAM 政策權限*：在 AWS 控制台中複製和更新 AWS 權限。
*** *EC2 IAM 執行個體設定檔權限*：在 AWS 控制台中複製並更新 Amazon EC2 執行個體上的 EC2 IAM 執行個體設定檔權限。
*** *部署模組*：如果需要，請選擇安裝依賴模組，包括 AWS 命令​​列介面 (AWS CLI)、jq（命令列 JSON 處理器）和 Python 3.12（如果尚未安裝 3.6 或更高版本）。工作負載工廠會在註冊過程中自動安裝這些模組。
*** *Oracle 使用者權限*：如果需要，更新 Oracle 使用者的權限。


.. 當先決條件完成並且檢查*準備就緒*時，您可以選擇*註冊*資料庫。




.結果
資料庫註冊啟動。選擇「作業監控」標籤來追蹤進度。

.下一步
資源註冊後，您可以執行以下操作。

* 從清單中查看資料庫
* link:create-database.html["建立資料庫"]
* link:create-sandbox-clone.html["建立資料庫克隆（沙盒）"]
* link:optimize-configurations.html["實施結構良好的資料庫配置"]

