---
sidebar: sidebar 
permalink: register-instance.html 
keywords: Microsoft SQL Server instance, PostgreSQL server instance, Oracle host instance, manage host, view host, database host, database instance, manage, unregister 
summary: 在資料庫的 BlueXP  工作負載工廠中管理 Microsoft SQL Server 執行個體。 
---
= 在資料庫工作負載工廠中註冊實例
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
註冊實例，以便您可以在資料庫工作負載工廠中監控實例和資料庫狀態、資源利用率、保護和儲存效能。

資料庫只能向 FSx for ONTAP 檔案系統儲存註冊實例。



== 關於任務

註冊實例包括兩個步驟 - 對實例進行驗證和準備實例，確保所有 AWS、NetApp 和 PowerShell 模組都安裝在實例上。

您可以使用 SQL Server 憑證或 Windows 憑證驗證連結。


NOTE: 工作負載工廠僅支援 Microsoft SQL Server 執行個體註冊和管理。根據您在工作負載工廠中選擇的 AWS 帳戶憑證，PostgreSQL 和 Oracle 主機可能會出現在清單中。目前，工作負載工廠僅支援在 Amazon Linux 作業系統上執行的未註冊 PostgreSQL 實例，以及僅在 Red Hat Enterprise Linux 上執行的 Oracle 執行個體。



== 在私有網路中註冊實例

若要在沒有外部連線的私有網路中註冊實例，下列端點需要在與 SQL 伺服器所在子網路關聯的 VPC 中可用。確保介面端點允許附加安全群組中的連接埠 443 。

* `S3 Gateway/endpoint`
* `ssm`
* `ssmmessages`
* `fsx`


如果您對 EC2 執行個體的所有傳出連線都使用 Proxy 伺服器，則必須允許存取下列網域，以便管理作業正常運作：

* ``.microsoft.com``
* ``.powershellgallery.com``
* ``.aws.amazon.com``
* ``.amazonaws.com``




== 開始之前

在註冊實例之前請考慮以下事項：

* 實例的主機必須顯示在「清單」標籤中。若要讓主機顯示在清單中， link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["您必須新增 AWS 帳戶憑證和「唯讀」或「讀取/寫入」模式權限"^] 。
* 使用 Windows 網域使用者憑證對 SQL Server 管理作業進行驗證時，工作負載工廠會在 SQL 節點上啟用 CredSSP 委派。如果使用群組原則封鎖所有網域電腦的 CredSSP 委派，則無法使用 Windows 使用者憑證進行驗證。




== 註冊實例

註冊實例包括實例認證和準備。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在「資料庫」方塊中、選取 * 前往資料庫庫存 * 。
. 在資料庫中、選取 * 庫存 * 索引標籤。
. 在「庫存」標籤中，選擇「*實例*」標籤。
. 選擇註冊單一實例或註冊多個實例。
+
.. 單一實例註冊：導航至要管理的實例並選擇*註冊實例*。
.. 多實例註冊：選擇*註冊多個實例*按鈕。
+
註冊多個實例有兩種方式。兩種情況下，實例必須具有相同的身份驗證狀態（未身份驗證或已身份驗證）。

+
*** 未經身份驗證的實例：選擇多個未經身份驗證的實例進行註冊。這些實例必須共用相同的驗證憑證和 FSx for ONTAP 憑證。選擇“應用”，然後選擇“下一步”。
*** 已認證實例：選擇多個已認證實例進行註冊，然後選擇*下一步*。




. 在「註冊實例」頁面的第 2 步中，選擇實例身份驗證模式，輸入以下詳細信息，然後選擇「下一步」。如果實例已通過身份驗證，請選擇「下一步」。
+
** *SQL Server 驗證*：輸入 SQL Server 使用者名稱和密碼，以及 FSx for ONTAP 檔案系統使用者名稱和密碼。
** *Windows 驗證*：輸入 Windows 使用者名稱和密碼，以及 FSx for ONTAP 檔案系統使用者名稱和密碼。


. 在步驟 3 中，透過確保實例滿足所需的先決條件來準備實例。如果所有必需模組均已安裝且先決條件均已滿足，請選擇「下一步」以註冊實例。如果您需要採取行動，請按照以下步驟操作。
+
.. 如果缺少，請選擇工作負載工廠來*安裝缺少的 AWS 和 NetApp PowerShell 模組*。
.. 如果缺少，請選擇「工作負載工廠」來「安裝缺少的 PowerShell 7」。安裝缺少的 PowerShell 模組 7 需要重新啟動系統。
.. 查看以下功能的先決條件清單。必須滿足一個先決條件才能註冊實例。
+
*** *審查精心設計的問題和建議*
*** *修復架構問題*
*** 建立資料庫
*** 建立資料庫副本（沙盒）
+
完成先決條件包括更新您的 AWS IAM 政策權限、EC2 IAM 執行個體設定檔權限、SQL Server 權限和 PowerShell 模組。



.. 完成至少一個缺失的先決條件才能繼續。
.. 當一個或多個先決條件完成並且檢查*準備就緒*時，您可以選擇*註冊*該實例。




.結果
實例註冊請求已發起。選擇「作業監控」標籤以追蹤進度。
